auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-12-08
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
  volume_enabled: true
  retention_period: 168h

#storage_config:
#  boltdb_shipper:
#    active_index_directory: /loki/index
#    cache_location: /loki/boltdb-cache
#    shared_store: filesystem
#  filesystem:
#    directory: /loki/chunks

#compactor:
#  working_directory: /loki/compactor
#  shared_store: filesystem
#


ruler:
  alertmanager_url: http://localhost:9093

#ruler:
#  storage:
#    type: local
#    local:
#      directory: /loki/rules
#  rule_path: /loki/rules
#  ring:
#    kvstore:
#      store: inmemory
#  enable_api: true