networks:
    loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - ./loki:/etc/loki/
      - ./loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - loki